#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: 750e50d
#
Name     : libdisplay-info
Version  : 0.1.1
Release  : 2
URL      : https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/0.1.1/libdisplay-info-0.1.1.tar.gz
Source0  : https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/0.1.1/libdisplay-info-0.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libdisplay-info-bin = %{version}-%{release}
Requires: libdisplay-info-lib = %{version}-%{release}
Requires: libdisplay-info-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : clr-hardware-files
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libdisplay-info
EDID and DisplayID library.
Goals:
- Provide a set of high-level, easy-to-use, opinionated functions as well as
low-level functions to access detailed information.
- Simplicity and correctness over performance and resource usage.
- Well-tested and fuzzed.

%package bin
Summary: bin components for the libdisplay-info package.
Group: Binaries
Requires: libdisplay-info-license = %{version}-%{release}

%description bin
bin components for the libdisplay-info package.


%package dev
Summary: dev components for the libdisplay-info package.
Group: Development
Requires: libdisplay-info-lib = %{version}-%{release}
Requires: libdisplay-info-bin = %{version}-%{release}
Provides: libdisplay-info-devel = %{version}-%{release}
Requires: libdisplay-info = %{version}-%{release}

%description dev
dev components for the libdisplay-info package.


%package lib
Summary: lib components for the libdisplay-info package.
Group: Libraries
Requires: libdisplay-info-license = %{version}-%{release}

%description lib
lib components for the libdisplay-info package.


%package license
Summary: license components for the libdisplay-info package.
Group: Default

%description license
license components for the libdisplay-info package.


%prep
%setup -q -n libdisplay-info-0.1.1
cd %{_builddir}/libdisplay-info-0.1.1
pushd ..
cp -a libdisplay-info-0.1.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707083424
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/libdisplay-info
cp %{_builddir}/libdisplay-info-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libdisplay-info/74e8e57a3b87c4cf0e0ab1d9b36e17a67e4b814e || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/di-edid-decode
/usr/bin/di-edid-decode

%files dev
%defattr(-,root,root,-)
/usr/include/libdisplay-info/cta.h
/usr/include/libdisplay-info/cvt.h
/usr/include/libdisplay-info/displayid.h
/usr/include/libdisplay-info/dmt.h
/usr/include/libdisplay-info/edid.h
/usr/include/libdisplay-info/gtf.h
/usr/include/libdisplay-info/info.h
/usr/lib64/libdisplay-info.so
/usr/lib64/pkgconfig/libdisplay-info.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libdisplay-info.so.0.1.1
/usr/lib64/libdisplay-info.so.0.1.1
/usr/lib64/libdisplay-info.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libdisplay-info/74e8e57a3b87c4cf0e0ab1d9b36e17a67e4b814e
