#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : libdisplay-info
Version  : 0.1.1
Release  : 1
URL      : https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/0.1.1/libdisplay-info-0.1.1.tar.gz
Source0  : https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/0.1.1/libdisplay-info-0.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libdisplay-info-bin = %{version}-%{release}
Requires: libdisplay-info-lib = %{version}-%{release}
Requires: libdisplay-info-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : clr-hardware-files
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libdisplay-info
EDID and DisplayID library.
Goals:
- Provide a set of high-level, easy-to-use, opinionated functions as well as
low-level functions to access detailed information.
- Simplicity and correctness over performance and resource usage.
- Well-tested and fuzzed.

%package bin
Summary: bin components for the libdisplay-info package.
Group: Binaries
Requires: libdisplay-info-license = %{version}-%{release}

%description bin
bin components for the libdisplay-info package.


%package dev
Summary: dev components for the libdisplay-info package.
Group: Development
Requires: libdisplay-info-lib = %{version}-%{release}
Requires: libdisplay-info-bin = %{version}-%{release}
Provides: libdisplay-info-devel = %{version}-%{release}
Requires: libdisplay-info = %{version}-%{release}

%description dev
dev components for the libdisplay-info package.


%package lib
Summary: lib components for the libdisplay-info package.
Group: Libraries
Requires: libdisplay-info-license = %{version}-%{release}

%description lib
lib components for the libdisplay-info package.


%package license
Summary: license components for the libdisplay-info package.
Group: Default

%description license
license components for the libdisplay-info package.


%prep
%setup -q -n libdisplay-info-0.1.1
cd %{_builddir}/libdisplay-info-0.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695752130
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libdisplay-info
cp %{_builddir}/libdisplay-info-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libdisplay-info/74e8e57a3b87c4cf0e0ab1d9b36e17a67e4b814e || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/di-edid-decode

%files dev
%defattr(-,root,root,-)
/usr/include/libdisplay-info/cta.h
/usr/include/libdisplay-info/cvt.h
/usr/include/libdisplay-info/displayid.h
/usr/include/libdisplay-info/dmt.h
/usr/include/libdisplay-info/edid.h
/usr/include/libdisplay-info/gtf.h
/usr/include/libdisplay-info/info.h
/usr/lib64/libdisplay-info.so
/usr/lib64/pkgconfig/libdisplay-info.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdisplay-info.so.0.1.1
/usr/lib64/libdisplay-info.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libdisplay-info/74e8e57a3b87c4cf0e0ab1d9b36e17a67e4b814e
